team: team419
######################
speed_go_straight: 50
speed_go_snow: 35
speed_process_tf: 45
speed_process_ob: 40
####################
angle_tf_left: -24
angle_tl_right: 20
angle_snow_left: -6
angle_snow_right: 5
####################
time_delay_tf_left: 0.5
time_delay_tf_right: 0.4
time_delay_ob_left: 0.25
time_delay_ob_right: 0.25
time_delay_snow_left: 0.7
time_delay_snow_right: 0.7
###########################
pos_ob : 25
limit_dis_lane: 100
limit_area_ob: 250
###########################
debug: False
