team: team419
######################
speed_go_straight: 50
speed_go_snow: 40
speed_process_tf: 40
speed_process_ob: 35
####################
angle_tf_left: -25
angle_tl_right: 25
####################
angle_snow_left: -12
angle_snow_right: 7
####################
time_delay_tf_left: 0.6
time_delay_tf_right: 0.6
########################
time_delay_ob_left: 0.3
time_delay_ob_right: 0.3
#########################
time_delay_snow_left: 0.9
time_delay_snow_right: 0.7
###########################
pos_ob : 25
limit_dis_lane: 100
limit_area_ob: 250
###########################
debug: False
