FROM dungpb/dira_ros:ros-python2-tensorflow

RUN sudo apt-get update
RUN sudo apt-get install python-tk -y
RUN pip install opencv-python imutils numpy Keras PyYAML==5.2 matplotlib

ADD team419.sh team419.sh

